-- =============================================================================
-- Rerunnable setup: drops existing objects then recreates tables with mock data
-- Compatible with Oracle 11g+ / XE / SQLcl / SQL*Plus
-- =============================================================================
SET DEFINE OFF;

-- ===================== HELPER: drop if exists ================================
-- Oracle has no IF EXISTS on DROP, so we use PL/SQL blocks.

-- 1) ORDERS depends on CUSTOMERS and PRODUCTS via FK
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
-- 2) PRODUCTS depends on CATEGORIES
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
-- 3) CATEGORIES (standalone)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
-- 4) CUSTOMERS (standalone)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
-- 5) EMPLOYEES (standalone)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
-- 6) AUDIT_LOG (standalone)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
-- 7) DOCUMENTS (standalone)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DOCUMENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
-- Drop sequences
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CUSTOMERS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PRODUCTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ORDERS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLOYEES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUDIT_LOG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CATEGORIES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

-- ===================== SEQUENCES =============================================
CREATE SEQUENCE SEQ_CATEGORIES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CUSTOMERS  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTS   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORDERS     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMPLOYEES  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDIT_LOG  START WITH 1 INCREMENT BY 1 NOCACHE;

-- ===================== TABLE: CATEGORIES =====================================
CREATE TABLE CATEGORIES (
    CATEGORY_ID   NUMBER        DEFAULT SEQ_CATEGORIES.NEXTVAL PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION   VARCHAR2(500),
    IS_ACTIVE     CHAR(1)       DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_CATEGORIES_NAME ON CATEGORIES(CATEGORY_NAME);

-- ===================== TABLE: CUSTOMERS ======================================
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID   NUMBER         DEFAULT SEQ_CUSTOMERS.NEXTVAL PRIMARY KEY,
    FIRST_NAME    VARCHAR2(50)   NOT NULL,
    LAST_NAME     VARCHAR2(50)   NOT NULL,
    EMAIL         VARCHAR2(120)  NOT NULL UNIQUE,
    PHONE         VARCHAR2(30),
    ADDRESS       VARCHAR2(200),
    CITY          VARCHAR2(80),
    COUNTRY       VARCHAR2(60),
    CREDIT_LIMIT  NUMBER(12,2)   DEFAULT 0,
    MEMBERSHIP    VARCHAR2(20)   DEFAULT 'STANDARD' CHECK (MEMBERSHIP IN ('STANDARD','SILVER','GOLD','PLATINUM')),
    DATE_OF_BIRTH DATE,
    REGISTERED_AT TIMESTAMP      DEFAULT SYSTIMESTAMP,
    NOTES         CLOB
);

CREATE INDEX IDX_CUSTOMERS_NAME    ON CUSTOMERS(LAST_NAME, FIRST_NAME);
CREATE INDEX IDX_CUSTOMERS_COUNTRY ON CUSTOMERS(COUNTRY);
CREATE INDEX IDX_CUSTOMERS_MEMBER  ON CUSTOMERS(MEMBERSHIP);

-- ===================== TABLE: PRODUCTS =======================================
CREATE TABLE PRODUCTS (
    PRODUCT_ID   NUMBER         DEFAULT SEQ_PRODUCTS.NEXTVAL PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(150)  NOT NULL,
    CATEGORY_ID  NUMBER         REFERENCES CATEGORIES(CATEGORY_ID),
    SKU          VARCHAR2(30)   NOT NULL UNIQUE,
    PRICE        NUMBER(10,2)   NOT NULL CHECK (PRICE >= 0),
    STOCK_QTY    NUMBER         DEFAULT 0,
    WEIGHT_KG    NUMBER(8,3),
    IS_AVAILABLE CHAR(1)        DEFAULT 'Y' CHECK (IS_AVAILABLE IN ('Y','N')),
    DESCRIPTION  VARCHAR2(1000),
    CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY_ID);
CREATE INDEX IDX_PRODUCTS_SKU      ON PRODUCTS(SKU);
CREATE INDEX IDX_PRODUCTS_PRICE    ON PRODUCTS(PRICE);

-- ===================== TABLE: ORDERS =========================================
CREATE TABLE ORDERS (
    ORDER_ID      NUMBER         DEFAULT SEQ_ORDERS.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID   NUMBER         NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
    PRODUCT_ID    NUMBER         NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY      NUMBER         NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE    NUMBER(10,2)   NOT NULL,
    TOTAL_AMOUNT  NUMBER(12,2)   GENERATED ALWAYS AS (QUANTITY * UNIT_PRICE) VIRTUAL,
    STATUS        VARCHAR2(20)   DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),
    ORDER_DATE    DATE           DEFAULT SYSDATE,
    SHIPPED_DATE  DATE,
    DELIVERY_NOTE VARCHAR2(500),
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDERS_PRODUCT  ON ORDERS(PRODUCT_ID);
CREATE INDEX IDX_ORDERS_STATUS   ON ORDERS(STATUS);
CREATE INDEX IDX_ORDERS_DATE     ON ORDERS(ORDER_DATE);

-- ===================== TABLE: EMPLOYEES ======================================
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID   NUMBER         DEFAULT SEQ_EMPLOYEES.NEXTVAL PRIMARY KEY,
    FIRST_NAME    VARCHAR2(50)   NOT NULL,
    LAST_NAME     VARCHAR2(50)   NOT NULL,
    EMAIL         VARCHAR2(120)  NOT NULL UNIQUE,
    PHONE         VARCHAR2(30),
    DEPARTMENT    VARCHAR2(60),
    JOB_TITLE     VARCHAR2(80),
    SALARY        NUMBER(12,2)   CHECK (SALARY >= 0),
    HIRE_DATE     DATE           DEFAULT SYSDATE,
    MANAGER_ID    NUMBER         REFERENCES EMPLOYEES(EMPLOYEE_ID),
    IS_ACTIVE     CHAR(1)        DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_EMPLOYEES_DEPT    ON EMPLOYEES(DEPARTMENT);
CREATE INDEX IDX_EMPLOYEES_MANAGER ON EMPLOYEES(MANAGER_ID);
CREATE INDEX IDX_EMPLOYEES_NAME    ON EMPLOYEES(LAST_NAME, FIRST_NAME);

-- ===================== TABLE: AUDIT_LOG ======================================
CREATE TABLE AUDIT_LOG (
    LOG_ID        NUMBER         DEFAULT SEQ_AUDIT_LOG.NEXTVAL PRIMARY KEY,
    TABLE_NAME    VARCHAR2(60)   NOT NULL,
    OPERATION     VARCHAR2(10)   NOT NULL CHECK (OPERATION IN ('INSERT','UPDATE','DELETE')),
    RECORD_ID     NUMBER,
    OLD_VALUE     CLOB,
    NEW_VALUE     CLOB,
    CHANGED_BY    VARCHAR2(60),
    CHANGED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_AUDIT_TABLE ON AUDIT_LOG(TABLE_NAME);
CREATE INDEX IDX_AUDIT_OP    ON AUDIT_LOG(OPERATION);
CREATE INDEX IDX_AUDIT_DATE  ON AUDIT_LOG(CHANGED_AT);

-- =============================================================================
-- MOCK DATA
-- =============================================================================

-- -------------------- CATEGORIES (6 rows) ------------------------------------
INSERT INTO CATEGORIES (CATEGORY_NAME, DESCRIPTION, IS_ACTIVE) VALUES ('Electronics',   'Phones, laptops, tablets and accessories', 'Y');
INSERT INTO CATEGORIES (CATEGORY_NAME, DESCRIPTION, IS_ACTIVE) VALUES ('Books',          'Fiction, non-fiction, textbooks',           'Y');
INSERT INTO CATEGORIES (CATEGORY_NAME, DESCRIPTION, IS_ACTIVE) VALUES ('Clothing',       'Men and women apparel',                    'Y');
INSERT INTO CATEGORIES (CATEGORY_NAME, DESCRIPTION, IS_ACTIVE) VALUES ('Home & Garden',  'Furniture, decor, gardening tools',        'Y');
INSERT INTO CATEGORIES (CATEGORY_NAME, DESCRIPTION, IS_ACTIVE) VALUES ('Sports',         'Equipment, apparel, nutrition',            'Y');
INSERT INTO CATEGORIES (CATEGORY_NAME, DESCRIPTION, IS_ACTIVE) VALUES ('Discontinued',   'Legacy products no longer sold',           'N');

-- -------------------- CUSTOMERS (12 rows) ------------------------------------
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Alice',   'Johnson',  'alice.johnson@example.com',   '+1-555-0101', '123 Maple St',      'New York',   'USA',       5000.00, 'GOLD',     DATE '1990-03-15', 'VIP customer since 2018');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Bob',     'Smith',    'bob.smith@example.com',       '+1-555-0102', '456 Oak Ave',       'Los Angeles','USA',       3000.00, 'SILVER',   DATE '1985-07-22', NULL);
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Charlie', 'Brown',    'charlie.brown@example.com',   '+44-20-7946', '10 Downing Rd',     'London',     'UK',        8000.00, 'PLATINUM', DATE '1978-11-30', 'International premium member');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Diana',   'Prince',   'diana.prince@example.com',    '+33-1-2345',  '8 Rue de Rivoli',   'Paris',      'France',    6000.00, 'GOLD',     DATE '1992-06-01', NULL);
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Ethan',   'Hunt',     'ethan.hunt@example.com',      '+1-555-0105', '789 Pine Blvd',     'Chicago',    'USA',       1000.00, 'STANDARD', DATE '1995-01-10', 'New customer');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Fiona',   'Green',    'fiona.green@example.com',     '+61-2-9876',  '42 Harbour St',     'Sydney',     'Australia', 4500.00, 'SILVER',   DATE '1988-09-18', NULL);
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('George',  'Wilson',   'george.wilson@example.com',   '+1-555-0107', '321 Elm Dr',        'Houston',    'USA',       2000.00, 'STANDARD', DATE '2000-12-25', NULL);
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Hannah',  'Lee',      'hannah.lee@example.com',      '+82-2-1234',  '55 Gangnam-daero',  'Seoul',      'South Korea',7000.00,'GOLD',     DATE '1993-04-08', 'Frequent buyer');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Ivan',    'Petrov',   'ivan.petrov@example.com',     '+7-495-1234', '12 Tverskaya St',   'Moscow',     'Russia',    3500.00, 'SILVER',   DATE '1982-08-14', NULL);
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Julia',   'Martinez', 'julia.martinez@example.com',  '+34-91-5678', '7 Gran Via',        'Madrid',     'Spain',     5500.00, 'GOLD',     DATE '1991-02-28', 'Prefers express shipping');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Kevin',   'Tanaka',   'kevin.tanaka@example.com',    '+81-3-9876',  '3-1 Shibuya',       'Tokyo',      'Japan',     9000.00, 'PLATINUM', DATE '1975-05-20', 'Corporate account');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, COUNTRY, CREDIT_LIMIT, MEMBERSHIP, DATE_OF_BIRTH, NOTES)
VALUES ('Laura',   'Muller',   'laura.muller@example.com',    '+49-30-5678', '15 Unter den Linden','Berlin',    'Germany',   4000.00, 'SILVER',   DATE '1997-10-03', NULL);

-- -------------------- PRODUCTS (15 rows) -------------------------------------
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Smartphone Pro 15',     1, 'ELEC-SP-001', 999.99,  120, 0.189, 'Y', 'Latest flagship smartphone with 6.7" OLED display');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Laptop Ultra 14',       1, 'ELEC-LT-002', 1499.00, 45,  1.400, 'Y', '14-inch ultrabook, 16GB RAM, 512GB SSD');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Wireless Earbuds X',    1, 'ELEC-WE-003', 149.50,  300, 0.055, 'Y', 'Active noise cancellation, 24h battery');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Tablet Air 11',         1, 'ELEC-TB-004', 599.00,  80,  0.460, 'Y', '11-inch tablet with stylus support');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('The Great Novel',       2, 'BOOK-FI-001', 14.99,   500, 0.350, 'Y', 'Bestselling fiction novel of the year');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Learn SQL in 30 Days',  2, 'BOOK-NF-002', 39.99,   200, 0.600, 'Y', 'Comprehensive SQL guide for beginners');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Go Programming Bible',  2, 'BOOK-NF-003', 49.99,   150, 0.720, 'Y', 'Advanced Go programming techniques');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Winter Jacket Deluxe',  3, 'CLTH-JK-001', 189.00,  60,  1.200, 'Y', 'Waterproof winter jacket, unisex');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Running Shoes Aero',    3, 'CLTH-SH-002', 129.99,  90,  0.680, 'Y', 'Lightweight running shoes with cushion sole');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Standing Desk Pro',     4, 'HOME-DK-001', 449.00,  25,  28.500,'Y', 'Electric height-adjustable standing desk');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Garden Tool Set',       4, 'HOME-GT-002', 59.99,   110, 3.200, 'Y', '12-piece stainless steel garden tool kit');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Yoga Mat Premium',      5, 'SPRT-YM-001', 34.99,   200, 1.100, 'Y', 'Non-slip 6mm thick yoga mat');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Dumbbell Set 20kg',     5, 'SPRT-DB-002', 79.99,   70,  20.000,'Y', 'Adjustable dumbbell pair, 2-20kg each');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('Protein Powder 2kg',    5, 'SPRT-PP-003', 44.99,   180, 2.100, 'Y', 'Whey protein isolate, chocolate flavour');
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, SKU, PRICE, STOCK_QTY, WEIGHT_KG, IS_AVAILABLE, DESCRIPTION)
VALUES ('VHS Player Classic',    6, 'DISC-VP-001', 29.99,   5,   3.500, 'N', 'Discontinued VHS player, limited stock');

-- -------------------- EMPLOYEES (10 rows) ------------------------------------
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('Sarah',   'Connor',   'sarah.connor@company.com',   '+1-555-1001', 'Engineering',  'VP Engineering',     180000.00, DATE '2015-01-10', NULL, 'Y');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('John',    'Reese',    'john.reese@company.com',     '+1-555-1002', 'Engineering',  'Senior Developer',   120000.00, DATE '2017-03-20', 1,    'Y');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('Kyle',    'Bishop',   'kyle.bishop@company.com',    '+1-555-1003', 'Engineering',  'Junior Developer',    65000.00, DATE '2023-06-01', 2,    'Y');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('Maria',   'Santos',   'maria.santos@company.com',   '+1-555-1004', 'Engineering',  'DevOps Engineer',     95000.00, DATE '2020-09-15', 1,    'Y');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('Tom',     'Hardy',    'tom.hardy@company.com',      '+1-555-1005', 'Sales',        'Sales Director',     150000.00, DATE '2016-02-28', NULL, 'Y');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('Emma',    'Stone',    'emma.stone@company.com',     '+1-555-1006', 'Sales',        'Account Manager',     85000.00, DATE '2019-11-01', 5,    'Y');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('James',   'Fox',      'james.fox@company.com',      '+1-555-1007', 'Sales',        'Sales Representative', 55000.00, DATE '2024-01-15', 6,    'Y');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('Olivia',  'Park',     'olivia.park@company.com',    '+1-555-1008', 'HR',           'HR Manager',         100000.00, DATE '2018-04-10', NULL, 'Y');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('Liam',    'Chen',     'liam.chen@company.com',      '+1-555-1009', 'Finance',      'Finance Director',   160000.00, DATE '2016-07-01', NULL, 'Y');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE, DEPARTMENT, JOB_TITLE, SALARY, HIRE_DATE, MANAGER_ID, IS_ACTIVE)
VALUES ('Noah',    'Wright',   'noah.wright@company.com',    '+1-555-1010', 'Engineering',  'QA Engineer',         72000.00, DATE '2022-03-14', 1,    'N');

-- -------------------- ORDERS (20 rows) ---------------------------------------
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (1,  1,  1, 999.99,  'DELIVERED',  DATE '2025-01-05', DATE '2025-01-08', 'Leave at front door');
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (1,  5,  2, 14.99,   'DELIVERED',  DATE '2025-01-05', DATE '2025-01-07', NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (2,  9,  1, 129.99,  'SHIPPED',    DATE '2025-02-10', DATE '2025-02-13', NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (3,  2,  1, 1499.00, 'DELIVERED',  DATE '2025-01-20', DATE '2025-01-25', 'Signature required');
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (3, 12,  2, 34.99,   'DELIVERED',  DATE '2025-02-01', DATE '2025-02-04', NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (4,  8,  1, 189.00,  'CONFIRMED',  DATE '2025-03-01', NULL,              'Gift wrap please');
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (5,  6,  3, 39.99,   'PENDING',    DATE '2025-03-15', NULL,              NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (6,  3,  2, 149.50,  'SHIPPED',    DATE '2025-02-20', DATE '2025-02-23', NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (7, 14,  1, 44.99,   'DELIVERED',  DATE '2025-01-30', DATE '2025-02-02', NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (8,  4,  1, 599.00,  'DELIVERED',  DATE '2025-02-14', DATE '2025-02-18', 'Valentine gift');
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (9, 10,  1, 449.00,  'CONFIRMED',  DATE '2025-03-10', NULL,              'Deliver to office');
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (10, 7,  2, 49.99,   'SHIPPED',    DATE '2025-03-05', DATE '2025-03-08', NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (11, 1,  1, 999.99,  'PENDING',    DATE '2025-03-20', NULL,              NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (12,11,  3, 59.99,   'CONFIRMED',  DATE '2025-03-18', NULL,              NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (1, 13,  1, 79.99,   'SHIPPED',    DATE '2025-03-12', DATE '2025-03-14', NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (3,  3,  1, 149.50,  'CANCELLED',  DATE '2025-02-28', NULL,              'Customer requested cancellation');
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (5, 15,  1, 29.99,   'DELIVERED',  DATE '2025-01-15', DATE '2025-01-20', 'Handle with care');
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (8,  9,  2, 129.99,  'PENDING',    DATE '2025-03-22', NULL,              NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (6,  7,  1, 49.99,   'DELIVERED',  DATE '2025-02-05', DATE '2025-02-09', NULL);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS, ORDER_DATE, SHIPPED_DATE, DELIVERY_NOTE)
VALUES (11, 4,  1, 599.00,  'CONFIRMED',  DATE '2025-03-25', NULL,              'Express delivery');

-- -------------------- AUDIT_LOG (8 rows) -------------------------------------
INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUE, NEW_VALUE, CHANGED_BY)
VALUES ('CUSTOMERS', 'INSERT', 1, NULL, '{"FIRST_NAME":"Alice","LAST_NAME":"Johnson"}', 'SYSTEM');
INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUE, NEW_VALUE, CHANGED_BY)
VALUES ('CUSTOMERS', 'UPDATE', 5, '{"CREDIT_LIMIT":500}', '{"CREDIT_LIMIT":1000}', 'admin');
INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUE, NEW_VALUE, CHANGED_BY)
VALUES ('PRODUCTS',  'UPDATE', 15, '{"IS_AVAILABLE":"Y"}', '{"IS_AVAILABLE":"N"}', 'admin');
INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUE, NEW_VALUE, CHANGED_BY)
VALUES ('ORDERS',    'UPDATE', 16, '{"STATUS":"PENDING"}', '{"STATUS":"CANCELLED"}', 'customer_service');
INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUE, NEW_VALUE, CHANGED_BY)
VALUES ('EMPLOYEES', 'UPDATE', 10, '{"IS_ACTIVE":"Y"}', '{"IS_ACTIVE":"N"}', 'hr_admin');
INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUE, NEW_VALUE, CHANGED_BY)
VALUES ('PRODUCTS',  'INSERT', 15, NULL, '{"PRODUCT_NAME":"VHS Player Classic","SKU":"DISC-VP-001"}', 'SYSTEM');
INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUE, NEW_VALUE, CHANGED_BY)
VALUES ('CUSTOMERS', 'UPDATE', 3, '{"MEMBERSHIP":"GOLD"}', '{"MEMBERSHIP":"PLATINUM"}', 'loyalty_program');
INSERT INTO AUDIT_LOG (TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUE, NEW_VALUE, CHANGED_BY)
VALUES ('ORDERS',    'INSERT', 20, NULL, '{"CUSTOMER_ID":11,"PRODUCT_ID":4,"STATUS":"CONFIRMED"}', 'web_app');

-- -------------------- DOCUMENTS ------------------------------------------
CREATE TABLE DOCUMENTS (
    DOCUMENT_ID   NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DOC_NAME      VARCHAR2(200)  NOT NULL,
    DOC_TYPE      VARCHAR2(50)   NOT NULL,
    FILE_SIZE     NUMBER(12)     DEFAULT 0,
    UPLOADED_BY   VARCHAR2(100),
    UPLOADED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP,
    DESCRIPTION   VARCHAR2(500),
    FILE_CONTENT  BLOB,
    THUMBNAIL     BLOB,
    METADATA      CLOB
);

-- -------------------- DOCUMENTS data (5 rows) --------------------------------
-- Row 1: small CSV file in BLOB
INSERT INTO DOCUMENTS (DOC_NAME, DOC_TYPE, FILE_SIZE, UPLOADED_BY, DESCRIPTION, FILE_CONTENT, THUMBNAIL, METADATA)
VALUES (
    'customers_export.csv',
    'text/csv',
    512,
    'admin',
    'Monthly customer export',
    UTL_RAW.CAST_TO_RAW('id,first_name,last_name,email,country' || CHR(10) ||
        '1,Alice,Johnson,alice@example.com,USA' || CHR(10) ||
        '2,Bob,Smith,bob@example.com,UK' || CHR(10) ||
        '3,Charlie,Brown,charlie@example.com,Canada' || CHR(10) ||
        '4,Diana,Prince,diana@example.com,Australia' || CHR(10) ||
        '5,Eve,Adams,eve@example.com,Germany' || CHR(10) ||
        '6,Frank,Castle,frank@example.com,France' || CHR(10) ||
        '7,Grace,Hopper,grace@example.com,USA' || CHR(10) ||
        '8,Hank,Pym,hank@example.com,UK' || CHR(10) ||
        '9,Iris,West,iris@example.com,Canada' || CHR(10) ||
        '10,Jack,Sparrow,jack@example.com,Australia'),
    NULL,
    '{"source":"crm","version":"1.0","columns":["id","first_name","last_name","email","country"]}'
);

-- Row 2: product price list CSV
INSERT INTO DOCUMENTS (DOC_NAME, DOC_TYPE, FILE_SIZE, UPLOADED_BY, DESCRIPTION, FILE_CONTENT, THUMBNAIL, METADATA)
VALUES (
    'product_prices.csv',
    'text/csv',
    384,
    'inventory_mgr',
    'Current product price list',
    UTL_RAW.CAST_TO_RAW('sku,product_name,price,category,in_stock' || CHR(10) ||
        'ELEC-LP-001,Laptop Pro 15,999.99,Electronics,Y' || CHR(10) ||
        'ELEC-SP-002,Smartphone X,599.00,Electronics,Y' || CHR(10) ||
        'ELEC-TW-003,True Wireless Earbuds,149.50,Electronics,Y' || CHR(10) ||
        'BOOK-PY-004,Python Programming,49.99,Books,Y' || CHR(10) ||
        'BOOK-DG-005,Data Science Guide,44.99,Books,N' || CHR(10) ||
        'HOME-CF-006,Coffee Maker Deluxe,129.99,Home,Y' || CHR(10) ||
        'SPRT-YM-007,Yoga Mat Premium,29.99,Sports,Y' || CHR(10) ||
        'ELEC-SC-008,Smart Watch Series 5,449.00,Electronics,Y'),
    NULL,
    '{"source":"inventory","version":"2.1","generated_at":"2025-03-01"}'
);

-- Row 3: binary-like data (simulated image thumbnail)
INSERT INTO DOCUMENTS (DOC_NAME, DOC_TYPE, FILE_SIZE, UPLOADED_BY, DESCRIPTION, FILE_CONTENT, THUMBNAIL, METADATA)
VALUES (
    'company_logo.png',
    'image/png',
    2048,
    'marketing',
    'Official company logo PNG',
    HEXTORAW('89504E470D0A1A0A0000000D49484452000000100000001008020000009001' ||
             '2E00000030494441547801016F00900000FF000000FF000000FF000000FF00' ||
             '0000FF000000FF000000FF000000FF000000FF000000FF000000FF000000FF' ||
             '000000FF000000FF000000FF000000FF000000FF000000FF000000FF000000'),
    HEXTORAW('89504E470D0A1A0A0000000D494844520000000800000008080200000004' ||
             '6BE96500000018494441540801016F00900000FF000000FF000000FF0000'),
    '{"width":256,"height":256,"color_depth":24,"format":"PNG","dpi":72}'
);

-- Row 4: large CSV report (order history)
INSERT INTO DOCUMENTS (DOC_NAME, DOC_TYPE, FILE_SIZE, UPLOADED_BY, DESCRIPTION, FILE_CONTENT, THUMBNAIL, METADATA)
VALUES (
    'order_history_q1_2025.csv',
    'text/csv',
    1024,
    'reports_svc',
    'Q1 2025 order history report',
    UTL_RAW.CAST_TO_RAW('order_id,customer_id,product_id,quantity,unit_price,status,order_date' || CHR(10) ||
        '1,1,2,1,599.00,DELIVERED,2025-01-10' || CHR(10) ||
        '2,2,5,2,44.99,DELIVERED,2025-01-12' || CHR(10) ||
        '3,3,8,1,129.99,DELIVERED,2025-01-15' || CHR(10) ||
        '4,4,1,1,999.99,DELIVERED,2025-01-20' || CHR(10) ||
        '5,5,12,3,59.99,DELIVERED,2025-01-25' || CHR(10) ||
        '6,6,3,2,149.50,SHIPPED,2025-02-20' || CHR(10) ||
        '7,7,14,1,44.99,DELIVERED,2025-01-30' || CHR(10) ||
        '8,8,4,1,599.00,DELIVERED,2025-02-14' || CHR(10) ||
        '9,9,10,1,449.00,CONFIRMED,2025-03-10' || CHR(10) ||
        '10,10,7,2,49.99,SHIPPED,2025-03-05' || CHR(10) ||
        '11,11,1,1,999.99,PENDING,2025-03-20' || CHR(10) ||
        '12,12,11,3,59.99,CONFIRMED,2025-03-18' || CHR(10) ||
        '13,1,13,1,79.99,SHIPPED,2025-03-12' || CHR(10) ||
        '14,3,3,1,149.50,CANCELLED,2025-02-28' || CHR(10) ||
        '15,5,15,1,29.99,DELIVERED,2025-01-15'),
    NULL,
    '{"report_type":"order_history","quarter":"Q1","year":2025,"row_count":15}'
);

-- Row 5: document with NULL blob (no file uploaded yet)
INSERT INTO DOCUMENTS (DOC_NAME, DOC_TYPE, FILE_SIZE, UPLOADED_BY, DESCRIPTION, FILE_CONTENT, THUMBNAIL, METADATA)
VALUES (
    'pending_upload.pdf',
    'application/pdf',
    0,
    'user_42',
    'Placeholder - file not yet uploaded',
    NULL,
    NULL,
    '{"status":"pending","expected_size_kb":250}'
);

COMMIT;
PROMPT === Mock data setup complete ===
PROMPT Tables created: CATEGORIES, CUSTOMERS, PRODUCTS, ORDERS, EMPLOYEES, AUDIT_LOG, DOCUMENTS
PROMPT Row counts: CATEGORIES=6, CUSTOMERS=12, PRODUCTS=15, ORDERS=20, EMPLOYEES=10, AUDIT_LOG=8, DOCUMENTS=5
